const dummyplaces = [
  {
    name: "High Court Metro Station Chennai (CMRL)",
    address: "Esplanade Rd, Parrys, George Town, Chennai, Tamil Nadu 600104",
    latCord: 13.08741164,
    longCord: 80.28515957,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: true,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.2,
    acsource: true,
    dcsource: true,
  },
  {
    name: "Koyam Bedu Metro Station, Chennai (CMRL)",
    address: "Koyambedu, Chennai, Tamil Nadu 600107",
    latCord: 13.07378059,
    longCord: 80.19509917,
    acType1: true,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 4.3,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Anna Nagar East Metro Station, Chennai (CMRL)",
    address: "2nd Ave, Block E, Annanagar East, Chennai, Tamil Nadu 600102",
    latCord: 13.0850044,
    longCord: 80.21863953,
    acType1: true,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 3.8,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Nandanam Metro station Chennai (CMRL)",
    address:
      "Metro Station Nandanam, Mount Rd, Rathna Nagar, Alwarpet, Chennai, Tamil Nadu 600035",
    latCord: 13.03608903,
    longCord: 80.24011623,
    acType1: true,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 4.1,
    acsource: true,
    dcsource: false,
  },
  {
    name: "HPCL COCO, Anna Auto Transport Drivers Industrial Cooperative Society Limited",
    address:
      "242, Royapettah High Rd, Azad Nagar, Royapettah, Chennai, Tamil Nadu 600014",
    latCord: 13.0502214,
    longCord: 80.26420064,
    acType1: true,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.6,
    acsource: true,
    dcsource: true,
  },
  {
    name: "IOC SRI SAI BALAJI AGENCIES",
    address:
      "25GG+958, Aminjikarai, 736, Poonamallee High Road, Chennai, Tamil Nadu 600029",
    latCord: 13.02863009,
    longCord: 80.17505298,
    acType1: true,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 50,
    reviewRating: 4.2,
    acsource: true,
    dcsource: true,
  },
  {
    name: "IOCL M/s Immanuel Agencies",
    address:
      "Lock No 1114, Plot No 1 & 2, 122, Mount Poonamallee Rd, near Park Dugar, Ramapuram, Kanchipuram, Tamil Nadu 600089",
    latCord: 13.02915587,
    longCord: 80.17540756,
    acType1: true,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 24,
    reviewRating: 4.3,
    acsource: true,
    dcsource: true,
  },
  {
    name: "MSHSD Mega Fuels Agency -HPCL",
    address:
      "Hpcl Dealers Plot NO. 90-B, Fishing Harbour Complex, Royapuram, Chennai, Tamil Nadu 600013",
    latCord: 13.12721617,
    longCord: 80.29517979,
    acType1: true,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 50,
    reviewRating: 4.7,
    acsource: true,
    dcsource: true,
  },
  {
    name: "EESL - Kannappar Thidal, Park Town Charging Station",
    address:
      "DPI office, Subba Road Avenue, Nungambakkam, Chennai, Tamil Nadu 600006",
    latCord: 13.07163673,
    longCord: 80.25105123,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 3.8,
    acsource: false,
    dcsource: true,
  },
  {
    name: "The Leela Palace (Private - Charger)",
    address:
      "Somerset Greenways, 94, Sathyadev Ave, MRC Nagar, Raja Annamalai Puram, Chennai, Tamil Nadu 600028",
    latCord: 13.02129388,
    longCord: 80.26976226,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 3.5,
    acsource: true,
    dcsource: true,
  },
  {
    name: "Tata Power - Taj Wellington Mews",
    address:
      "TRIL Infopark Limited, Rajiv Gandhi Salai, Tharamani, Chennai, Tamil Nadu 600113",
    latCord: 12.99643681,
    longCord: 80.24912813,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.2,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Charger - Sarvam Apartment Charging Station",
    address:
      "S&S Sarvam, 318/A, 200 Feet Radial Rd, Ganesh Avenue, Rose Avenue, Pallikaranai, Chennai, Tamil Nadu 600100",
    latCord: 12.94845584,
    longCord: 80.20355578,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 4.3,
    acsource: false,
    dcsource: true,
  },
  {
    name: "MG - Motors (FPL Vehicles)",
    address: "824/2, Anna Salai, Sadras, Nandanam, Chennai, Tamil Nadu 600035",
    latCord: 13.0231223,
    longCord: 80.22699211,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: true,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 25,
    reviewRating: 4.5,
    acsource: false,
    dcsource: true,
  },
  {
    name: "IOCL - PORUR Charging Station",
    address:
      "88, Kundrathur Main Rd, MS Nagar, Porur, Chennai, Tamil Nadu 600116",
    latCord: 13.02841709,
    longCord: 80.14985025,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 60,
    reviewRating: 4.8,
    acsource: false,
    dcsource: true,
  },
  {
    name: "EESL - Saidapet Metro Charging Station",
    address: "Periyapet, Saidapet, Chennai, Tamil Nadu 600015",
    latCord: 13.02407596,
    longCord: 80.22718037,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: true,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.4,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Ather Energy Pvt Ltd - Madipakkam Charging Station",
    address:
      "93, Bazaar Main Rd, Ram Nagar Police check post, Ram Nagar South, Madipakkam, Chennai, Tamil Nadu 600091",
    latCord: 12.96604697,
    longCord: 80.2098551,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.7,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata Power - Ginger Hotel vadapalni(Privat - Charger )",
    address:
      "Smart Towers, 100 Feet Rd, Thiru Nagar Colony, NGO Colony, Vadapalani, Chennai, Tamil Nadu 600026",
    latCord: 13.05680457,
    longCord: 80.21117965,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 50,
    reviewRating: 3.6,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Mahindra - Chennai Egmore metro Charging Station",
    address:
      "37H6+MH5, Chennai Egmore metro car parking, Chennai, Tamil Nadu 600008",
    latCord: 13.07937525,
    longCord: 80.26155037,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 3.8,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Velachery Charging Station",
    address:
      "The Westin, 154, Velachery Main Rd, TN Police Housing Colony, Velachery, Chennai, Tamil Nadu 600042",
    latCord: 12.98999457,
    longCord: 80.22089071,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.2,
    acsource: true,
    dcsource: false,
  },
  {
    name: "COC - Perungudi Charging Station",
    address:
      "Level 7,No:143, IIFL TOWERS, MGR Main Rd, Govindasamy Nagar, Perungudi, Chennai, Tamil Nadu 96",
    latCord: 12.96683451,
    longCord: 80.24650486,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.3,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Kazam - Thiruvottiyur Charging Station",
    address:
      "Parijatham Plot no 12, 11th Main Rd, Vaishnavi Nagar Main Rd, West Gandhi Nagar, Indira Gandhi Nagar, Thirumullaivoyal, Chennai, Tamil Nadu 600062",
    latCord: 13.12791087,
    longCord: 80.12852108,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: true,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.2,
    acsource: true,
    dcsource: false,
  },
  {
    name: "EESL - Alandur Metro Charging Station",
    address: "Alandur, Chennai, Tamil Nadu 600016",
    latCord: 13.00433298,
    longCord: 80.20148245,
    acType1: false,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: true,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 25,
    reviewRating: 4.3,
    acsource: true,
    dcsource: true,
  },
  {
    name: "Tata Power - Trident Chennai Charging Station",
    address:
      "1, 24, Grand Southern Trunk Rd, Kannan Colony, Meenambakkam, Chennai, Tamil Nadu 600027",
    latCord: 12.99429177,
    longCord: 80.18615328,
    acType1: false,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: true,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.7,
    acsource: true,
    dcsource: true,
  },
  {
    name: "Tata Power - Taj Connemara, Anna Salai (Private - Charger)",
    address: "Binny Rd, Anna Salai, Chennai, Tamil Nadu 600002",
    latCord: 13.0630304,
    longCord: 80.26148443,
    acType1: false,
    acType2: false,
    dc001: true,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: true,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.4,
    acsource: true,
    dcsource: true,
  },
  {
    name: "DPI Office Charging Station",
    address:
      "EVK SAMPATH MALIGAI, College Rd, Subba Road Avenue, Nungambakkam, Chennai, Tamil Nadu 600008",
    latCord: 13.06915512,
    longCord: 80.25094317,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: true,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 50,
    reviewRating: 3.5,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Relux EV Charging",
    address:
      "Flyover Bridge, Dr.M.G.R Educational and Research Institute Maduravoyal Bypass, junction, Service Rd, East wing, Maduravoyal, Chennai, Tamil Nadu 600095",
    latCord: 13.07746857,
    longCord: 80.1623002,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 24,
    reviewRating: 4.2,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Minooki EV Charger",
    address:
      "Somerset Greenways, 94, Sathyadev Ave, MRC Nagar, Raja Annamalai Puram, Chennai, Tamil Nadu 600028",
    latCord: 13.02748907,
    longCord: 80.27289621,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 24,
    reviewRating: 3.8,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Revolt EV Charger",
    address:
      "4/47, Aziz Mulk 1st St, Thousand Lights West, Thousand Lights, Chennai, Tamil Nadu 600006",
    latCord: 13.06422771,
    longCord: 80.25675954,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 3.5,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Lectron EV Charging",
    address:
      "Century Plaza, No:560 to 562, Anna Salai, Thiru Vi Ka Kudiyiruppu, Teynampet, Chennai, Tamil Nadu 600018",
    latCord: 13.05511957,
    longCord: 80.24611578,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 4.2,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Kazam EV Charging",
    address:
      "4-1394, 4th Block, Mogappair West, Ambattur Industrial Estate, Chennai, Tamil Nadu 600037",
    latCord: 13.08362706,
    longCord: 80.168694,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 3.6,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Esplanade EV Charger",
    address:
      "37QP+65F, Esplanade Rd, Parrys, George Town, Chennai, Tamil Nadu 600104",
    latCord: 13.08890061,
    longCord: 80.28545434,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 60,
    reviewRating: 4.1,
    acsource: false,
    dcsource: true,
  },
  {
    name: "L&T EV Charger",
    address:
      "Nearer to TCTC BUILDING, L & T EDRC BUILDING, Manapakkam, Chennai, Tamil Nadu 600125",
    latCord: 13.02385216,
    longCord: 80.17899709,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 60,
    reviewRating: 3.2,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Zeon Charging Station",
    address:
      "Grand Chennai, 120, Sir Thyagaraya Rd, Drivers Colony, T. Nagar, Chennai, Tamil Nadu 600017",
    latCord: 13.04053003,
    longCord: 80.2451731,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 4.1,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata Power Charging Station",
    address: "100, 48, Cathedral Rd, Gopalapuram, Chennai, Tamil Nadu 600086",
    latCord: 13.04680926,
    longCord: 80.2554577,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: true,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 25,
    reviewRating: 4.1,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata EV Charging Station",
    address: "105, Race Course Rd, Puliakulam, Coimbatore, Tamil Nadu 641018",
    latCord: 11.0086637,
    longCord: 76.97491407,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 60,
    reviewRating: 3.9,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata EV Charger",
    address:
      "SF No 128 Singanallur, Trichy Rd, Neelikonampalayam, Tamil Nadu 641005",
    latCord: 11.00765268,
    longCord: 77.03636884,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.3,
    acsource: false,
    dcsource: true,
  },
  {
    name: "VEEV Charging Station",
    address:
      "LG - 22, B1, Dr Krishnasamy Mudaliyar Rd, Puthiyavan Nagar, Sukrawar Pettai, R.S. Puram, Coimbatore, Tamil Nadu 641001",
    latCord: 11.00928749,
    longCord: 76.95934908,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.7,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata Power Charging Station",
    address: "105, Race Course Rd, Puliakulam, Coimbatore, Tamil Nadu 641018",
    latCord: 11.0025925,
    longCord: 76.97347752,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 50,
    reviewRating: 4.1,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Ather Grid Charging Station",
    address:
      "Chai Kings, No. 546 and 567, NSR Rd, Near Pulimaram Bus Stop, Saibaba Colony, Coimbatore, Tamil Nadu 641011",
    latCord: 11.02701884,
    longCord: 76.94857194,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 4.7,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Relux EV Charging Station",
    address:
      "KMCH, Avinashi Rd, TNHB Colony, Indira Nagar, Civil Aerodrome Post, Coimbatore, Tamil Nadu 641014",
    latCord: 11.0405252,
    longCord: 77.04101337,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.8,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tucker EV Charging",
    address:
      "W22W+C6Q, near Anna University, Srinivasa Colony, Kilakuyilkudi, Tamil Nadu 625006",
    latCord: 9.90213467,
    longCord: 78.04546061,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.3,
    acsource: true,
    dcsource: true,
  },
  {
    name: "Zeon Melanesaneri station",
    address:
      "Hotel Temple City, NH 44, Madurai to Virudhunagar, Highways, Melanesaneri, Madurai, Tamil Nadu 625706",
    latCord: 9.780904768,
    longCord: 77.97639345,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.9,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata Power Salem Charger",
    address: "M4MG+4C4, Salem, Tamil Nadu 636004",
    latCord: 11.74210394,
    longCord: 78.13345217,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 25,
    reviewRating: 3.7,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Dollar EV Charging Station",
    address:
      "Hotel Sai Annapoorna, Sandiyur Attayampatti, Salem, Tamil Nadu 636203",
    latCord: 11.57865668,
    longCord: 78.14583412,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.2,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Zeon Salem station",
    address:
      "Aasai Aasai Anandha Bhavan Delight, NH - 44 Bangalore, to, Salem Highway, Omalur, Tamil Nadu 636455",
    latCord: 11.75553583,
    longCord: 78.05109598,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.6,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Tata Power Charging Station",
    address: "W6W2+46Q, Vellore, Tamil Nadu 632009",
    latCord: 13.34311283,
    longCord: 79.19617044,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.1,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Zeon Vellore Station",
    address: "NH 48 Service Rd, Thottapalayam, Vellore, Tamil Nadu 632012",
    latCord: 12.93233333,
    longCord: 79.13855354,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.9,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Ather Grid Charging Station",
    address:
      "No.71,72,73, 2nd Floor, Selvam Square, Inox Selvam Cinemas, Tiruvalam Rd, Selvam Nagar, Katpadi, Vellore, Tamil Nadu 632007",
    latCord: 12.96820862,
    longCord: 79.15050244,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 4.6,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Ather Grid Hosur",
    address:
      "no.88 and 89, PALLAVI RETAIL PVT.LTD, Indira Nagar, Sri Nagar, Hosur, Tamil Nadu 635109",
    latCord: 12.73803407,
    longCord: 77.8298772,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 7.4,
    reviewRating: 4.4,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Kazam EV charging point",
    address:
      "Survey No 322/1b, 2b, 3b, Hosur - Krishnagiri Rd, Nallaganakothapalli, Tamil Nadu 635117",
    latCord: 12.6728068,
    longCord: 77.98026337,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.5,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Zeon Ooty Point",
    address: "Gem Park Ooty, Sheddon Rd, Pudumund, Ooty, Tamil Nadu 643001",
    latCord: 11.4206733,
    longCord: 76.70422654,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 4.7,
    acsource: false,
    dcsource: true,
  },
  {
    name: "My EV India Charging Point",
    address: "CP95+2WM, Garden Rd, Vannarapettai, Ooty, Tamil Nadu 643002",
    latCord: 11.41828516,
    longCord: 76.70966598,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: true,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 90,
    reviewRating: 4.6,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Relux EV charging station ooty",
    address: "CP73+HJ5, Pudumund, Ooty, Tamil Nadu 643001",
    latCord: 11.41441506,
    longCord: 76.70400116,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.9,
    acsource: false,
    dcsource: true,
  },
  {
    name: "Bolt EV Charging Station",
    address:
      "84A, Devaraya Nagar, Krishna Moorthy Nagar, K K Nagar, Tiruchirappalli, Tamil Nadu 620021",
    latCord: 10.8457267,
    longCord: 78.6597081,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 4.3,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Ather Charging station",
    address:
      "20/C113, 5th Cross, Thillai Nagar, Tiruchirappalli, Tamil Nadu 620018",
    latCord: 10.82746533,
    longCord: 78.68544082,
    acType1: false,
    acType2: true,
    dc001: false,
    ccs1: false,
    ccs2: false,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 3.3,
    reviewRating: 4.4,
    acsource: true,
    dcsource: false,
  },
  {
    name: "Zeon Charging Station",
    address:
      "TATA Motors Kaveri, Grand Southern Trunk Rd, Srirangam, Thiruvanaikoil, Tiruchirappalli, Tamil Nadu 620005",
    latCord: 10.85794946,
    longCord: 78.71156734,
    acType1: false,
    acType2: false,
    dc001: false,
    ccs1: false,
    ccs2: true,
    bharatAc001: false,
    bharatDc001: false,
    ac001: false,
    chademo: false,
    teslaCharger: false,
    gbt: false,
    acplugpnt: false,
    powerRating: 30,
    reviewRating: 3.9,
    acsource: false,
    dcsource: true,
  },
];

const stationData = dummyplaces.map((place) => {
  const slotValue = Math.floor(Math.random() * (4 - 2 + 1)) + 2;
  const val1 = Math.floor(Math.random() * (50 - 20 + 1)) + 20;
  const val2 = Math.floor(Math.random() * (40 - 15 + 1)) + 15;
  const val3 = Math.floor(Math.random() * (60 - 30 + 1)) + 30;
  const val4 = Math.floor(Math.random() * (40 - 25 + 1)) + 25;

  const newdata = {
    name: place.name,
    address: place.address,
    latitude: place.latCord,
    longitude: place.longCord,
    acType1: place.acType1,
    acType2: place.acType2,
    dcType1: place.ccs1,
    dcType2: place.ccs2,
    powerRating: place.powerRating,
    review: place.reviewRating,
    phone_number: "+917305882025",
    acsource: place.acsource,
    dcsource: place.dcsource,
    slots: slotValue,
    acType1Cost: val1,
    acType2Cost: val2,
    dcType1Cost: val3,
    dcType2Cost: val4,
    timeInterval: [
      [510, 690],
      [810, 990],
      [1110, 1290],
    ],
  };
  return newdata;
});

const pool = require("./config/db");

const insertStations = async (req, res) => {
  try {
    const values = await stationData.map(
      (data) => [
        data.name,
        data.address,
        data.latitude,
        data.longitude,
        data.acType1,
        data.acType2,
        data.dcType1,
        data.dcType2,
        data.powerRating,
        data.review,
        data.phone_number,
        data.acsource,
        data.dcsource,
        1
      ]
    );

    const query = `INSERT INTO station (name,
        address,
        lat,
        lng,
        ac1,
        ac2,
        dc1,
        dc2,
        power,
        review,
        phone_number,
        ac_type,
        dc_type,
        u_id
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`;

    values.map(async (data) => {
      const result = await pool.query(query, data);
    })
    console.log("success");
  } catch (err) {
    console.error("Insert error:", err);
  }
};


const insertAvailable = async (req, res) => {
  try {
    const values = [];
    for (let i = 1; i < 2; i++) {
      tmp = [i, "10:40:00", "12:30:00", "2025-06-30", 3, 20, 3];
      values.push(tmp);
    }
    const query = `INSERT INTO available (s_id,
        av_start_time,
        av_end_time,
        av_book_date,
        av_slots,
        cost,
        counter
        ) VALUES ($1,$2,$3,$4,$5,$6,$7)`;

    values.map(async (data) => {
      const result = await pool.query(query, data);
    })
    console.log("success");
  } catch (err) {
    console.error("Insert error:", err);
  }
};

const deleteAvailable = async (req, res) => {
  try {
    const query = `DELETE FROM available`;

    const result = await pool.query(query);
    console.log("success");
  } catch (err) {
    console.error("Insert error:", err);
  }
};

const FormattedDate = (dateObj) => {
  const yyyy = dateObj.getFullYear();
  const mm = String(dateObj.getMonth() + 1).padStart(2, '0'); // Months are 0-based
  const dd = String(dateObj.getDate()).padStart(2, '0');

  const formattedDate = `${yyyy}-${mm}-${dd}`;
  return formattedDate
}

const getAvailable = async (req, res) => {
  try {
    const query = `SELECT * FROM available WHERE s_id=$1`;
    const result = await pool.query(query, [1]);
    console.log(result.rows);
    const currentDateTime = Date.now();
    console.log(currentDateTime)
    const dates = result.rows.map((data) => {
      const newDate = FormattedDate(data.av_book_date) + 'T' + data.av_start_time;
      const availableDateTime = new Date(newDate);
      console.log(newDate, "newdate")
      if (currentDateTime < availableDateTime) {
        return data.av_book_date + " " + data.av_start_time;
      } else return "date expires"
    })
    console.log("success", dates);
  } catch (err) {
    console.error("Insert error:", err);
  }
}

insertAvailable()